import { ROUTES } from "@/shared/config";

export const hiddenCtaPaths: Array<string | RegExp> = [
	ROUTES.USER_RESET_PASSWORD,
	ROUTES.USER_SIGNUP,
	ROUTES.USER_SIGNUP_VERIFICATION,
	ROUTES.LEGAL_PRIVACY,
	ROUTES.LEGAL_TERMS,
	ROUTES.LEGAL_COOKIES,
];
